config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'posts#index'
  get 'posts' => 'posts#index'
  resources :posts do
    resources :comments
    resources :likes
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_attached_file :image, :styles => { :large => "500x500", :medium => "400x400>", :thumb => "100x100>" },
                    :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :commented_posts, through: :comments, source: :post

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username
  validates_uniqueness_of :username

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    if @comment.save
      @comment.user_id = current_user.id
      @comment.username = current_user.username
      @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def destroy
    @comment = Comment.find(params[:post_id])
    @comment.destroy
    flash[:notice] = 'Comment deleted successfully'
    redirect_to '/posts'
  end

  private

  def comment_params
    params.require(:comment).permit(:thoughts)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post.likes.create
    render json: {new_like_count: @post.likes.count}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      @post.user_id = current_user.id
      @post.username = current_user.username
      @post.save
      redirect_to '/posts'
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = 'Post deleted successfully'
    redirect_to '/posts'
  end

  private

  def post_params
    params.require(:post).permit(:description, :image)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def relative_time(creation_time)
    diff = TimeDifference.between(creation_time, Time.now).in_general
    if diff[:weeks] > 0 || diff[:months] > 0 || diff[:years] > 0
      return "Over a week ago"
    elsif diff[:days] == 1
      return "1 day ago"
    elsif diff[:days] > 0
      return "#{diff[:days]} days ago"
    elsif diff[:hours] == 1
      return "1 hour ago"
    elsif diff[:hours] > 0
      return "#{diff[:hours]} hours ago"
    elsif diff[:minutes] == 1
      return "1 minute ago"
    elsif diff[:minutes] > 0
      return "#{diff[:minutes]} minutes ago"
    elsif diff[:seconds] == 1
      return "1 second ago"
    elsif diff[:seconds] > 0
      return "#{diff[:seconds]} seconds ago"
    else
      return "Just now"
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/comments/new.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.text_area :thoughts, :placeholder => "Add a comment.."%>
  </br></br>
  <%= f.submit "Post" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emstagram</title>
      <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet"/>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
      <link href="https://fonts.googleapis.com/css?family=Noto Sans" type="text/css" rel="stylesheet"/>
      <link href="https://fonts.googleapis.com/css?family=Lobster Two" type="text/css" rel="stylesheet"/>
      <link href="https://fonts.googleapis.com/css?family=Permanent Marker" type="text/css" rel="stylesheet"/>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="navbar navbar-default navbar-static-top" role="navigation" id="navbar">
      <div class="container" id="navbar-container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Emstagram</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav" id="search-form">
            <form id="search-bar">
              <input type="search" placeholder="Search">
            </form>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><a href="<%= new_user_session_path %>">Login</a></li>
              <li><a href="<%= new_user_registration_path %>">Sign Up</a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="container container container" id="main-container">
      <p><%= notice %></p>
      <p><%= yield %></p>
    </div>
  </body>

</html>

app/views/posts/index.html.erb
<% if current_user %>
  <b><%= link_to "Post a photo", '/posts/new', class:"link"%></b>
<% else %>
  Please sign in to post a photo
<% end %>
</br></br>
  <div class="central">
    <% if @posts.any? %>
      <% @posts.reverse.each do |post| %>
        <div class="well well-lg" id="well">
          <span id="username">@<%= post.username %></span>
          <span id="timestamp"><%= relative_time(post.created_at) %></span>
          </br></br>
          <%= link_to image_tag(post.image.url(:large)), post_path(post), id: post.id %>
          </br></br>
          <span id="description"><%= post.description %></span>
          </br></br>
          <% if current_user %>
            <%= link_to post_likes_path(post), class:"link", id:"likes-link" do %>
              <span class="glyphicon glyphicon-heart"></span>
            <% end %>
            <span class="likes_count"> <%= post.likes.count %> </span> <%= 'like'.pluralize post.likes.count %>
          <% else %>
            <span class="glyphicon glyphicon-heart"></span>
            <span class="likes_count"> <%= post.likes.count %> </span> <%= 'like'.pluralize post.likes.count %>
          <% end %>
          </br></br>
          <% if current_user %>
            <% if (post.user_id == current_user.id) %>
              <%= link_to "Delete post", post_path(post), method: :delete, class:"link", id:"delete" %>
            <% end %>
          <% end %>
        </br></br>
        </div>
      <% end %>
    <% else %>
      No photos posted
    <% end %>
  </div>

app/views/posts/new.html.erb
<%= form_for @post, html: {multipart: true} do |f| %>
  <%= f.file_field :image, required: 'Image required' %>
  <%= f.text_field :description, :placeholder => "Add a caption" %>
  <%= f.submit "Post" %>
<% end %>

app/views/posts/show.html.erb
<div class="central">
  <div class="well well-lg" id="well">
    <span id="username">@<%= @post.username %></span>
    <span id="timestamp"><%= relative_time(@post.created_at) %></span>
    </br></br>
    <p><%= image_tag @post.image.url(:large) %></p>
    <p id="description"><%= @post.description %></p>
    <% if @post.comments.any? %>
      <ul>
        <% @post.comments.each do |comment| %>
          <ol id="comments">
            <span id="comment_user">@<%=comment.username%></span> <%=comment.thoughts%>
          </ol>
        <% end %>
      </ul>
    <% else %>
      No comments yet
    </br></br>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to "Add comment", new_post_comment_path(@post), class:"link" %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path, class:"link" %> to add a comment
    <% end %>
  </div>
</div>